create extension if not exists "pgcrypto";

create table if not exists public.user (
  id uuid primary key default gen_random_uuid(),
  discord_id text unique,
  username text not null,
  profile_name text,
  avatar_url text,
  is_bot boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.guild (
  id text unique not null,
  name text not null,
  owner_id text references public.user(id) on delete set null,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guild_settings (
  guild_id text not null references public.guild(id) on delete cascade,
  message_count integer not null default 0,
  token_balance integer not null default 0,
  token_limit integer not null default 1000,
  token_total_usage integer not null default 0,
  primary key (guild_id)
);

create table if not exists public.guild_member (
  guild_id text not null references public.guild(id) on delete cascade,
  user_id uuid not null references public.user(id) on delete cascade,
  display_name text,
  roles jsonb not null default '[]'::jsonb,
  joined_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_rolled_at timestamptz,
  primary key (guild_id, user_id),
  unique (user_id, guild_id)
);

create table if not exists public.guild_tts_settings (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guild(id) on delete cascade,
  replies_enabled boolean not null default true,
  room_prefix_enabled boolean not null default false,
  tts_channel_name text not null default 'tts',
  female_voice_id text,
  male_voice_id text,
  idle_timeout_seconds integer not null default 600 check (idle_timeout_seconds > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guild_command_settings (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guild(id) on delete cascade,
  command_name text not null,
  enabled boolean not null default true,
  settings jsonb not null default '{}'::jsonb,
  updated_by_user_id uuid references public.user(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guild_id, command_name)
);

create table if not exists public.guild_chat_logs (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guild(id) on delete cascade,
  channel_id text not null,
  voice_channel_id text,
  user_id uuid references public.user(id) on delete set null,
  message_id text unique,
  raw_message text not null,
  spoken_message text,
  tts_mode text not null default 'channel' check (tts_mode in ('channel', 'room_prefix')),
  created_at timestamptz not null default now()
);

create table if not exists public.pokemon (
  id bigint generated by default as identity primary key,
  handle text not null unique,
  pokedex_id bigint not null,
  form_id bigint not null,
  name text not null,
  form_name text,
  sprites jsonb,
  height integer,
  weight integer,
  capture_rate integer,
  gender_rate integer,
  is_baby boolean not null default false,
  is_legendary boolean not null default false,
  is_mythical boolean not null default false,
  flavor_text text,
  created_at timestamptz not null default now(),
  unique (pokedex_id, form_id)
);

create table if not exists public.user_pokemon (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  profile_id text not null references public.guild_member(id) on delete cascade,
  pokemon_id bigint not null references public.pokemon(id) on delete cascade,
  shiny boolean not null default false,
  unique (profile_id, pokemon_id, shiny)
);

create index if not exists guild_chat_logs_guild_created_idx
  on public.guild_chat_logs (guild_id, created_at desc);

create index if not exists guild_command_settings_guild_idx
  on public.guild_command_settings (guild_id);

create index if not exists guild_member_idx
  on public.guild_member (guild_id);

create index if not exists user_pokemon_profile_idx
  on public.user_pokemon (profile_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger guilds_set_updated_at
  before update on public.guild
  for each row execute function public.set_updated_at();

create trigger guild_tts_settings_set_updated_at
  before update on public.guild_tts_settings
  for each row execute function public.set_updated_at();

create trigger guild_command_settings_set_updated_at
  before update on public.guild_command_settings
  for each row execute function public.set_updated_at();


alter table public.user enable row level security;
alter table public.guild enable row level security;
alter table public.guild_settings enable row level security;
alter table public.guild_member enable row level security;
alter table public.guild_tts_settings enable row level security;
alter table public.guild_command_settings enable row level security;
alter table public.guild_chat_logs enable row level security;
alter table public.pokemon enable row level security;
alter table public.user_pokemon enable row level security;
