create table if not exists public.pokemon (
  id bigint generated by default as identity primary key,
  handle text not null unique,
  pokedex_id bigint not null,
  form_id bigint not null,
  name text not null,
  form_name text,
  sprites jsonb,
  height integer,
  weight integer,
  capture_rate integer,
  gender_rate integer,
  is_baby boolean not null default false,
  is_legendary boolean not null default false,
  is_mythical boolean not null default false,
  flavor_text text,
  created_at timestamptz not null default now(),
  unique (pokedex_id, form_id)
);

create table if not exists public.user_pokemon (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id text not null references public.guild_members(user_id) on delete cascade,
  pokemon_id bigint not null references public.pokemon(id) on delete cascade,
  shiny boolean not null default false,
  unique (user_id, pokemon_id, shiny)
);


alter table public.pokemon enable row level security;
alter table public.user_pokemon enable row level security;